spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: example_route
          uri: http://httpbin.org:80
          predicates:
            - Path=/get/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
